accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name = 'signup'),
    path('login/', views.login_view, name = 'login'),
    path('logout/', views.logout_view, name = 'logout')
]

articles/urls.py
from django.contrib import admin
from django.urls import path

from articles import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name = 'list'),
    path('create', views.article_create, name = 'create'),
    path('<slug:slug>', views.article_item, name='article_detail'),
    path('update/<slug:slug>', views.article_update, name = 'update'),
    path('delete/<slug:slug>', views.article_delete, name = 'delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite import views
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_views.article_list, name = 'homepage'),
    path('about/', views.about, name = 'about'),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 200)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumbnail = models.ImageField(upload_to='images/', blank=True, default='images/default.png')
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)


    def __str__(self):
        return self.title
    
    def snippet(self):
       return self.body[0:50] + '...'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from django.contrib.auth import password_validation

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "class": "form-control mb-3"}))
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "class": "form-control mb-3"}),
    )

class SignupForm(UserCreationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "class": "form-control mb-3"}))
    password1 = forms.CharField(
        label="Password",
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control mb-3"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        required=True,
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", "class": "form-control mb-3"}),
        help_text="Enter the same password as before, for verification.",
    )

articles/forms.py
from django import forms

from . import models

class ArticleForm(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'thumbnail']
        labelsa = {
            "title": "Title",
            "body": "Text",
            "thumbnail": "Thumbnail"
        }
        widgets = {
            "title": forms.TextInput(attrs={'placeholder': 'Write article title', 'class': 'form-control mb-3'}),
            "body": forms.TextInput(attrs={'placeholder': 'Write article text', 'class': 'form-control mb-3'}),
            "thumbnail": forms.ClearableFileInput(attrs={'class': 'form-control mb-3'}),
        }

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponseRedirect

from accounts.forms import SignupForm, LoginForm

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect('/articles')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('articles:list')
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
    return HttpResponseRedirect('/articles')

articles/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from articles.models import Article
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles' : articles})

def article_item(request, slug):
    articles = Article.objects.all().order_by('date')
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_item.html', {'article': article, 'articles' : articles})

@login_required(login_url = 'accounts:login')
def article_create(request):
    if request.method == 'POST':
        form = forms.ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('homepage')
    else:
        form = forms.ArticleForm()
    return render(request, 'articles/article_form.html', {'form': form})

@login_required(login_url='accounts:login')
def article_update(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        if request.method == 'POST':
            form = forms.ArticleForm(request.POST, request.FILES, instance = article)
            if form.is_valid():
                instance = form.save(commit = False)
                instance.author = request.user
                instance.save()
                return redirect('articles:article_detail', slug=article.slug)
        else:
            form = forms.ArticleForm(instance=article)
        return render(request, 'articles/article_form.html', {'form': form})
    return HttpResponse('401 Unauthorized', status = 401)

@login_required(login_url='accounts:login')
def article_delete(request, slug):
    article = Article.objects.get(slug=slug)
    if request.user.id == article.author.id:
        if request.method == 'POST':
            article.delete()
            return redirect('homepage')
        return render(request, 'articles/article_confirm_delete.html', {'article': article})
    return HttpResponse('401 Unauthorized', status = 401)

mysite/views.py
from django.shortcuts import render

def homepage(request):
    data = {"header": "Homepage", "message": "Welcome to My Site!"}
    return render(request, 'homepage.html', context=data)

def about(request):
    header = "About us"
    staff = ['John Nichols', 'John Rogers', 'Timothy Smith']
    director = {"name": "David Lee", "img": '/director.jpg'}
    address = ('20 W 34th St.', 'New York', 'NY 10001', 'USA')
    data = {"header": header, "staff": staff, "director": director, "address": address}
    return render(request, 'about.html', data)

accounts/templates/accounts/login.html
{% extends "articles/base_layout.html" %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}
<h1>Login</h1>

<div class = "container">
    <div class ="row g-4 justify-content-center">
        <div class = "col-md-8 col-lg-6">
            <form class = "form" action ="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {{ form }}
                {% if request.GET.next %}
                    <input type = "hidden" name = "next" value="{{ request.GET.next }}">
                {% endif %}
                <button type = "submit" class = "btn">Login</button>
                <a href="{% url 'accounts:signup' %}" class = "btn">Signup</a>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "articles/base_layout.html" %}
{% load static %}
{% block title %}Sign Up{% endblock title %}

{% block content %}
<h1>SignUp</h1>
<div class = "container">
    <div class ="row g-4 justify-content-center">
        <div class = "col-md-8 col-lg-6">
            <form class = "form" action ="/accounts/signup/" method="post">
                {% csrf_token %}
                {{ form }}
                <button type = "submit">Sign up</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

articles/templates/articles/article_confirm_delete.html
{% extends "articles/base_layout.html" %}
{% load static %}
{% block title %}{{ article.title }}{% endblock title %}
{% block content %}
<div class = "container">
    <div class ="row g-4 justify-content-center">
        <div class = "col-md-8 col-lg-6">
            <div class = "article-confirm-delete">
                <h1 class = "mb-3">Are you sure?</h1>
                <form class = "form" method = "post">
                    {% csrf_token %}
                    <button type = "submit" class = "btn">Yes</button>
                    <a href="{% url 'homepage' %}" class="btn">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

articles/templates/articles/article_form.html
{%extends "articles/base_layout.html" %}
{% load static %}
{% block title %}Create or update article{% endblock title %}
{% block content %}
<h1>Create or update article</h1>
<div class = "container">
    <div class ="row g-4 justify-content-center">
        <div class = "col-md-8 col-lg-6">
            <form class = "form" method = "post" enctype = "multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <button type = "submit" class="btn">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

articles/templates/articles/article_item.html
{% extends "articles/base_layout.html" %}
{% block title %}{{ article.title }}{% endblock title %}
{%block content %}
<div class="article-detail">
    <h1>{{ article.title }}</h1>
    <p class = "article-p">{{ article.body }}</p>
    {% if article.thumbnail %}
    <img class = "article-img" src = "{{ article.thumbnail.url }}" alt = "">
    {% endif %}
    {% if user.is_authenticated and user.id == article.author.id %}
        <div>
            <a class = "btn"
                href = "{% url 'articles:update' slug=article.slug %}">
                Update
            </a>
            <a class = "btn"
                href = "{% url 'articles:delete' slug=article.slug %}">
                Delete
            </a>
        </div>
    {% endif %}
</div>
{% endblock content %}

articles/templates/articles/article_list.html
{%extends "articles/base_layout.html" %}
{%block title %}Article List{% endblock title %}
{%block content %}
<main>
    <h1>Article List</h1>
    <div class="articles">
        <div class = "container">
            <div class ="row g-4">
                {% for element in articles %}
                <div class ="col-lg-4">
                    <div class="article__item">
                        <h2>
                            <a href="{% url 'articles:article_detail' slug=element.slug %}">
                                {{ element.title }}
                            </a>
                        </h2>
                        <p>
                            {{ element.snippet }}
                        </p>
                        <time>
                            {{ element.date }}
                        </time>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>


    </div>
    
    
</main>
{% endblock content %}

articles/templates/articles/base_layout.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
</head>

<body>
    <header>
        <nav class = "navigation">
            <div class="container">
                <div class = "navigation_wrap">
                    <a href="{% url 'homepage' %}">
                        <img src="{% static '/img/logo.png' %}" alt="logo">
                    </a>
                    {% if user.is_authenticated %}
                    <form class="form_logout" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class = "btn">Logout</button>
                    </form>
                    <a href="{% url 'articles:create' %}" class = "btn">Create article</a>
                    {% else %}
                        <a class = "btn" href ="{% url 'accounts:login' %}">Login</a>
                        <a class = "btn " href="{% url 'accounts:signup' %}">Sign up</a>
                    {% endif %}
                </div>
            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
        crossorigin="anonymous"></script>
</body>

</html>

templates/about.html
<!DOCTYPE html>
<html lang ="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>{{ header }}</h1>
    <p>Director: {{ director.name }}</p>
    <p>Address: {{ address.0 }}, {{ address.1 }}, {{ address.2 }}, {{ address.3 }}</p>
    <p>Staff: {{ staff.0 }}, {{ staff.1 }}, {{ staff.2 }}</p>
</body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang ="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>{{ header }}</h1>
    <p>{{ message }}</p>
</body>
</html>